### ISSUE TITLE
test failure archlinux - python 3.5

### ISSUE THREAD

**Issue by sciunto** [soft-matter/trackpy#288]
with 0.2.4
```
======================================================================
ERROR: test_annotate (test_plots.TestPlots)  
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fr/aur4/python-trackpy/src/trackpy-0.2.4/trackpy/tests/test_plots.py", line 59, in test_annotate
    self.assertRaises(bad_call)
  File "/usr/lib/python3.5/unittest/case.py", line 724, in assertRaises
    return context.handle('assertRaises', args, kwargs)

```

with rc1

```
======================================================================
ERROR: test_annotate (trackpy.tests.test_plots.TestPlots)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fr/aur4/python-trackpy/src/trackpy-0.3.0rc1/trackpy/tests/test_plots.py", line 69, in test_annotate
    self.assertRaises(bad_call)
  File "/usr/lib/python3.5/unittest/case.py", line 724, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.5/unittest/case.py", line 157, in handle
    (name, self._base_type_str))
TypeError: assertRaises() arg 1 must be an exception type or tuple of exception types

----------------------------------------------------------------------
Ran 324 tests in 149.681s
```

**Comment by sciunto** [comment]
Thanks @danielballan As soon as another rc release is pushed, I'll make a new package for arch.
