### ISSUE TITLE
Test failure with Pandas 0.17

### ISSUE THREAD

**Issue by anntzer** [soft-matter/trackpy#295]
```
======================================================================
FAIL: test_zero_emsd (test_motion.TestMSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/makepkg/python-trackpy/src/trackpy-0.2.4/trackpy/tests/test_motion.py", line 136, in test_zero_emsd
    assert_series_equal(actual, expected)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 903, in assert_series_equal
    obj='{0}.index'.format(obj))
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 673, in assert_index_equal
    assert_attr_equal('names', left, right, obj=obj)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 708, in assert_attr_equal
    left_attr, right_attr)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series.index are different

Attribute "names" are different
[left]:  ['lagt']
[right]: [None]
```

**Comment by nkeim** [comment]
We are testing trackpy with Python 3.5 and this error does not occur. Can you reproduce the reported failure with a more recent version of trackpy? You can also report the output of `import trackpy.diag; trackpy.diag.dependencies()`

**Comment by anntzer** [comment]
With the current HEAD, this doesn't happen anymore, but now `test_link.test_copy` fails when checking for UserWarning, as pandas 0.17 now raises a FutureWarning at that spot.

**Comment by nkeim** [comment]
@anntzer Thank you! I'm going to reference #299 and #282 as this pertains to the sticky issue of Pandas 0.17 (because it's backwards-incompatible with Pandas 0.16.).
