### ISSUE TITLE
v0.3.0 : test failure pandas

### ISSUE THREAD

**Issue by sciunto** [soft-matter/trackpy#338]
Hi,

A quick note to report this:

```
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Index are different

Index classes are different
[left]:  Float64Index([0.0, 1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 5.0, 6.0, 6.0,
              7.0, 7.0, 8.0, 8.0, 9.0, 9.0],
             dtype='float64', name='frame')
[right]: Int64Index([0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9], dtype='int64', name='frame')

======================================================================
FAIL: test_zero_emsd (trackpy.tests.test_motion.TestMSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fr/aur4/python-trackpy/src/trackpy-0.3.0/trackpy/tests/test_motion.py", line 141, in test_zero_emsd
    assert_series_equal(actual, expected)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 924, in assert_series_equal
    obj='{0}.index'.format(obj))
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 653, in assert_index_equal
    _check_types(left, right)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 629, in _check_types
    raise_assert_detail(obj, msg, l, r)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Index are different

Index classes are different
[left]:  Float64Index([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0], dtype='float64', name='lagt')
[right]: Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64', name='lagt')

----------------------------------------------------------------------
Ran 332 tests in 167.391s

FAILED (SKIP=95, errors=1, failures=5)
```

I can check against master. If it's fixed in master, it would deserve an update. It's actually blocking for the archlinux package.

Thanks.

**Comment by nkeim** [comment]
Thanks. What is the pandas version?

On Jan 8, 2016, at 5:43 AM, Fran?ois Boulogne <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

A quick note to report this:

  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Index are different

Index classes are different
[left]:  Float64Index([0.0, 1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 5.0, 5.0, 6.0, 6.0,
              7.0, 7.0, 8.0, 8.0, 9.0, 9.0],
             dtype='float64', name='frame')
[right]: Int64Index([0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9], dtype='int64', name='frame')

======================================================================
FAIL: test_zero_emsd (trackpy.tests.test_motion.TestMSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fr/aur4/python-trackpy/src/trackpy-0.3.0/trackpy/tests/test_motion.py", line 141, in test_zero_emsd
    assert_series_equal(actual, expected)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 924, in assert_series_equal
    obj='{0}.index'.format(obj))
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 653, in assert_index_equal
    _check_types(left, right)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 629, in _check_types
    raise_assert_detail(obj, msg, l, r)
  File "/usr/lib/python3.5/site-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Index are different

Index classes are different
[left]:  Float64Index([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0], dtype='float64', name='lagt')
[right]: Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64', name='lagt')

----------------------------------------------------------------------
Ran 332 tests in 167.391s

FAILED (SKIP=95, errors=1, failures=5)


I can check against master. If it's fixed in master, it would deserve an update. It's actually blocking for the archlinux package.

Thanks.

-

**Comment by sciunto** [comment]
0.17.1

**Comment by caspervdw** [comment]
Current master is passing with pandas 0.17.1, after PR #330. So probably that fixes this error.

 If not, there is a fix in this test in #337, which has to do with float inprecision. But that one is not merged.

**Comment by sciunto** [comment]
I made a virtualenv and checked against master. This issue seems to be solved but I have another error:

```
======================================================================
ERROR: test_annotate3d (trackpy.tests.test_plots.TestPlots)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fr/github/trackpy/trackpy/tests/test_plots.py", line 94, in test_annotate3d
    plots.annotate3d(f, frame)
  File "/home/fr/github/trackpy/trackpy/plots.py", line 584, in annotate3d
    bbox_inches='tight')
  File "/usr/lib/python3.5/site-packages/pims/display.py", line 436, in plots_to_frame
    size = plot_to_frame(figures[0], 100, **imsave_kwargs).shape
  File "/usr/lib/python3.5/site-packages/pims/display.py", line 403, in plot_to_frame
    fig.savefig(buffer, format='tif', dpi=dpi, **imsave_kwargs)
  File "/usr/lib/python3.5/site-packages/matplotlib/figure.py", line 1539, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
    **kwargs)
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 594, in print_tif
    dpi=dpi)
  File "/usr/lib/python3.5/site-packages/PIL/Image.py", line 1665, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3.5/site-packages/PIL/TiffImagePlugin.py", line 1320, in _save
    offset = ifd.save(fp)
  File "/usr/lib/python3.5/site-packages/PIL/TiffImagePlugin.py", line 608, in save
    if len(data) <= 4:
TypeError: object of type 'int' has no len()
```

**Comment by sciunto** [comment]
I don't know if there is some relation with https://github.com/soft-matter/pims/pull/204

**Comment by caspervdw** [comment]
Yes this issue came up with PIL 3.0.0.  You can either roll back PIL to 2.9.0 or use the pims master.  Pims 0.3.3 will include the fix and will be released soon.

**Comment by sciunto** [comment]
Le 08/01/2016 19:12, Casper van der Wel a écrit :
> Yes this issue came up with PIL 3.0.0. You can either roll back PIL to
> 2.9.0 or use the pims master. Pims 0.3.3 will include the fix and will
> be released soon.
> 


Thank you. I need to patch or wait Pims 0.3.3 for the package on
archlinux. I cannot roll back PIL for that. I'll wait a little more if
it's upcoming :)

Best.

**Comment by caspervdw** [comment]
@sciunto  I just released pims 0.3.3, all tests should now pass with any Pillow version. Please give it a try!

**Comment by sciunto** [comment]
@caspervdw It works! Packages for archlinux are updated :)

Many thanks.

**Comment by sciunto** [comment]
I leave it open, we can close once the new trackpy is released.

**Comment by caspervdw** [comment]
What is our policy regarding closing solved issues? Close after release or close after merge? I am in for closing this as the solution was merged already.
