### ISSUE TITLE
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#422]
This is new, and seems a bit deep into predict to be caused by something I did, however I am guessing I'm causing the issue.

Traceback (most recent call last):
  File "lib\v\v.py", line 1793, in <module>
    main()
  File "lib\v\v.py", line 1765, in main
    omod.run(oc, ol, ou, modes, src)
  File "lib\v\v.py", line 1392, in run
    adaptive_step=trkdct['astep']
  File "lib\pandas\tools\merge.py", line 1451, in concat
    copy=copy)
  File "lib\pandas\tools\merge.py", line 1481, in __init__
    objs = list(objs)
  File "lib\trackpy\predict.py", line 52, in link_df_iter
    for frame in linking.link_df_iter(*args, **kw):
  File "lib\trackpy\linking.py", line 719, in link_df_iter
    labeled_levels, features_forpost, index_iter):
  File "lib\trackpy\linking.py", line 1025, in link
    prev_hash.rebuild(coord_map=targeted_predictor) # Rewrite positions
  File "lib\trackpy\linking.py", line 52, in rebuild
    coords = np.asarray(list(coord_map(self.points)))
  File "lib\trackpy\predict.py", line 169, in predict
    np.tile(t1 - times, (positions.shape[1], 1)).T)
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

**Comment by nkeim** [comment]
The "<U32" dtype is a 32-character unicode string. So that is why subtraction is not implemented. I think that if you make sure your frame numbers are integers this should work.

I guess this is a downside of the frame number being dtype-agnostic!

On Feb 12, 2017, at 12:06 PM, apiszcz <notifications@github.com<mailto:notifications@github.com>> wrote:


This is new, and seems a bit deep into predict to be caused by something I did, however I am guessing I'm causing the issue.

Traceback (most recent call last):
File "lib\v\v.py", line 1793, in
main()
File "lib\v\v.py", line 1765, in main
omod.run(oc, ol, ou, modes, src)
File "lib\v\v.py", line 1392, in run
adaptive_step=trkdct['astep']
File "lib\pandas\tools\merge.py", line 1451, in concat
copy=copy)
File "lib\pandas\tools\merge.py", line 1481, in init
objs = list(objs)
File "lib\trackpy\predict.py", line 52, in link_df_iter
for frame in linking.link_df_iter(*args, **kw):
File "lib\trackpy\linking.py", line 719, in link_df_iter
labeled_levels, features_forpost, index_iter):
File "lib\trackpy\linking.py", line 1025, in link
prev_hash.rebuild(coord_map=targeted_predictor) # Rewrite positions
File "lib\trackpy\linking.py", line 52, in rebuild
coords = np.asarray(list(coord_map(self.points)))
File "lib\trackpy\predict.py", line 169, in predict
np.tile(t1 - times, (positions.shape[1], 1)).T)
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

**Comment by apiszcz** [comment]
thanks, something happened to my data frame elsewhere.

df.info()
frame        152827 non-null object

**Comment by apiszcz** [comment]
All set.
