### ISSUE TITLE
trackpy installation problems with metaclass conflict/numpy version

### ISSUE THREAD

**Issue by willwxu** [soft-matter/trackpy#469]
I am installing trackpy on a fresh Anaconda2 installation and ran into the same issue as soft-matter/pims#276. I tried downgrading six from 1.11 to 1.9, but then ran into the following error:

`/anaconda2/lib/python2.7/site-packages/dask/array/numpy_compat.py:32: RuntimeWarning: divide by zero encountered in divide
  not np.allclose(np.divide(1, .5, dtype='i8'), 2) or
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/trackpy/__init__.py", line 11, in <module>
    from trackpy.api import *
  File "/anaconda2/lib/python2.7/site-packages/trackpy/api.py", line 10, in <module>
    from .plots import annotate, annotate3d, plot_traj, ptraj, \
  File "/anaconda2/lib/python2.7/site-packages/trackpy/plots.py", line 15, in <module>
    from pims import plot_to_frame, plots_to_frame, normalize
  File "/anaconda2/lib/python2.7/site-packages/pims/__init__.py", line 1, in <module>
    from pims.api import *
  File "/anaconda2/lib/python2.7/site-packages/pims/api.py", line 14, in <module>
    from pims.image_sequence import ImageSequence  # noqa
  File "/anaconda2/lib/python2.7/site-packages/pims/image_sequence.py", line 15, in <module>
    from skimage.io import imread
  File "/anaconda2/lib/python2.7/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/anaconda2/lib/python2.7/site-packages/skimage/util/__init__.py", line 5, in <module>
    from .apply_parallel import apply_parallel
  File "/anaconda2/lib/python2.7/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/anaconda2/lib/python2.7/site-packages/dask/array/__init__.py", line 15, in <module>
    from .ufunc import (add, subtract, multiply, divide, logaddexp, logaddexp2,
  File "/anaconda2/lib/python2.7/site-packages/dask/array/ufunc.py", line 138, in <module>
    cbrt = ufunc(np.cbrt)
AttributeError: 'module' object has no attribute 'cbrt'
`

This appeared to be the same issue as dask/dask#2596, which was resolved by updating numpy to at least 1.10. However, the trackpy install for Python 2.7 downgrades to numpy 1.9. Any advice would be greatly appreciated!

**Comment by willwxu** [comment]
Resolved it by installing pims first, which did not downgrade numpy, then installing trackpy and downgrading six to 1.9.

**Comment by asafira** [comment]
Is the word-around really to install things in a different order? Shouldn't this issue at least be flagged as a bug? (or maybe I'm missing something)

**Comment by tacaswell** [comment]
I suspect we need to re-build the conda packages against newer versions of numpy....
