### ISSUE TITLE
TST/BLD: Compatibility with Pandas 0.23.0

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#501]
Most of our testing is still with Pandas 0.18.0. The latest release raises many, many warnings on both Python 2.7 and 3.6, but on Python 3.6 it also causes many tests to fail. The errors all have the form

```
======================================================================
FAIL: test_two_nearby_steppers (trackpy.tests.test_legacy_linking.TestKDTreeWithNumbaLinkDiag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nkeim/trackpy/trackpy/tests/test_legacy_linking.py", line 394, in test_two_nearby_steppers
    assert_frame_equal(actual_iter, expected)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/pandas/util/testing.py", line 1323, in assert_frame_equal
    obj='{obj}.columns'.format(obj=obj))
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/pandas/util/testing.py", line 843, in assert_index_equal
    obj=obj, lobj=left, robj=right)
  File "pandas/_libs/testing.pyx", line 59, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 173, in pandas._libs.testing.assert_almost_equal
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/pandas/util/testing.py", line 1018, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.columns are different
DataFrame.columns values are different (75.0 %)
[left]:  Index(['frame', 'x', 'y', 'particle'], dtype='object')
[right]: Index(['x', 'y', 'frame', 'particle'], dtype='object')
```

**Comment by caspervdw** [comment]
I will try to fix the failures, warnings are for later

**Comment by Resonanz** [comment]
I am having some success with Pandas 0.23.4.  Version 0.24.2 was a show-stopper for me.
```
pip uninstall pandas
pip install pandas==0.23.4
```
