### ISSUE TITLE
CI tests fail with latest Pandas

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#529]
The latest Pandas release seems to be stricter about arguments to `sort_values`. Our tests raise many errors like the one reproduced below. It may be possible to fix these simply by editing trackpy's `pandas_sort()` function. This issue would be a great way to help with trackpy—it may be as simple as reading the Pandas release notes 😃.

```
======================================================================
ERROR: test_subtract_constant_drift (trackpy.tests.test_motion.TestDrift)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/trackpy/trackpy/tests/test_motion.py", line 48, in setUp
    self.dead_still = conformity(pandas_concat([a, b]))
  File "/home/travis/build/soft-matter/trackpy/trackpy/tests/test_motion.py", line 26, in conformity
    return pandas_sort(df, by=['frame', 'particle'])
  File "/home/travis/build/soft-matter/trackpy/trackpy/utils.py", line 317, in _pandas_sort_post_017
    return df.sort_values(*args, by=by, **kwargs)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/pandas/core/frame.py", line 4711, in sort_values
    for x in by]
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/pandas/core/frame.py", line 4711, in <listcomp>
    for x in by]
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/pandas/core/generic.py", line 1702, in _get_label_or_level_values
    self._check_label_or_level_ambiguity(key, axis=axis)
  File "/home/travis/mc/envs/testenv/lib/python3.6/site-packages/pandas/core/generic.py", line 1656, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: 'frame' is both an index level and a column label, which is ambiguous.
```

**Comment by caspervdw** [comment]
Another one:

```
ERROR: test_storage (trackpy.tests.test_feature_saving.TestPandasHDFStoreSingleNodeCompressed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/soft-matter/trackpy/trackpy/tests/test_feature_saving.py", line 64, in test_storage
    s = self.storage_class(STORE_NAME)
  File "/home/travis/build/soft-matter/trackpy/trackpy/framewise_data.py", line 251, in __init__
    with pd.get_store(self.filename) as store:
AttributeError: 'module' object has no attribute 'get_store'
```

**Comment by KrUciFieR-Jr** [comment]
Hey, @nkeim  I would like to work on this issue!

**Comment by nkeim** [comment]
@KrUciFieR-Jr Wonderful!! Please let us know how we can help.

**Comment by rbnvrw** [comment]
Additionally, pull request #538 now also fixes the `pd.get_store()` deprecation error.

**Comment by nkeim** [comment]
Thanks @rbnvrw ! I just posted a question about pytables. Otherwise your patch looks good and we should be able to resolve this soon.

**Comment by rbnvrw** [comment]
I have removed the pytables dependency, I added it because without it, the framewise_data does not work, but it is fine if it is optional.

**Comment by speedymcs** [comment]
Quick and dirty fix for anyone clueless who might end up here looking (like me):
`tracks.index.names = ["index"]`
