### ISSUE TITLE
Matplotlib and batchConvert failure

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#537]
Hi Guys, I have an issue that I wonder if you could help me with (I'm using the latest trackpy 0.41).

The code is quite simple and appears to run fine from the command line on my Mac but not within pyCharm. Here is the code, taken almost verbatim from the Walkthrough notebook:
```
import matplotlib as mpl
mpl.use('Agg')
#import matplotlib.pyplot as plt
#plt.ioff()         # Stop matplotlib popup windows

print(mpl.__version__)

import numpy as np
import pandas as pd
from pandas import DataFrame, Series  # for convenience

import pims
import trackpy as tp

frames = pims.ImageSequence('../tKinterTesting/bulk_water/*.png', as_grey=True)

f = tp.batch(frames[:10], 11, minmass=200, invert=True)
```

If I run this from the command line I get the following which seems to be perfect:

```
(base) it092023:deleteme2 rlward$ python delme.py
3.0.3
trackpy.feature.batch:  Frame 0: 297 features
trackpy.feature.batch:  Frame 1: 296 features
trackpy.feature.batch:  Frame 2: 304 features
trackpy.feature.batch:  Frame 3: 306 features
trackpy.feature.batch:  Frame 4: 304 features
trackpy.feature.batch:  Frame 5: 302 features
trackpy.feature.batch:  Frame 6: 305 features
trackpy.feature.batch:  Frame 7: 304 features
trackpy.feature.batch:  Frame 8: 297 features
trackpy.feature.batch:  Frame 9: 309 features
```

yet running this within the pyCharm editor gives this output:

```
/Users/rlward/.conda/envs/tKinterTesting/bin/python /Users/rlward/Documents/Github/deleteme2/delme.py
3.0.3
/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/site-packages/trackpy/refine/center_of_mass.py:233: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  neighborhood = mask*image[rect]
/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/site-packages/trackpy/refine/center_of_mass.py:275: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  raw_neighborhood = mask*raw_image[rect]
/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/site-packages/trackpy/feature.py:418: UserWarning: No maxima survived mass- and size-based filtering. Be advised that the mass computation was changed from version 0.2.4 to 0.3.0 and from 0.3.3 to 0.4.0. See the documentation and the convenience functions 'minmass_v03_change' and 'minmass_v04_change'.
  warnings.warn("No maxima survived mass- and size-based filtering. "
trackpy.feature.batch:  Frame 0: 0 features
trackpy.feature.batch:  Frame 1: 0 features
trackpy.feature.batch:  Frame 2: 0 features
trackpy.feature.batch:  Frame 3: 0 features
trackpy.feature.batch:  Frame 4: 0 features
trackpy.feature.batch:  Frame 5: 0 features
trackpy.feature.batch:  Frame 6: 0 features
trackpy.feature.batch:  Frame 7: 0 features
trackpy.feature.batch:  Frame 8: 0 features
/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/site-packages/trackpy/feature.py:600: UserWarning: No maxima found in any frame.
trackpy.feature.batch:  Frame 9: 0 features
  warnings.warn("No maxima found in any frame.")

Process finished with exit code 0
```

Now, the Walkthough code does give a bunch of warnings shown at the start of the output above, but I'm not referring to these in this post. I'm more curious as to why I'm getting 0 features found.

I'm guessing that it is related to Matplotlib, but I have no idea why. I say this because of this link:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000108710-Matplotlib-support-failed

Even with this simple code snippet...

```
import matplotlib as mpl
import matplotlib.pyplot as plt
```
...I get a failed build in pyCharm:

```
/Users/rlward/.conda/envs/tKinterTesting/bin/python /Users/rlward/Documents/Github/deleteme2/delme.py
Traceback (most recent call last):
  File "/Users/rlward/Documents/Github/deleteme2/delme.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/rlward/.conda/envs/tKinterTesting/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

Process finished with exit code 1
```

**Comment by nkeim** [comment]
What do you get for `max(frames[0])` in each case?

It may be that in the absence of other image-reader packages, pims is falling back to using matplotlib as an image reader.

**Comment by nkeim** [comment]
Closing due to inactivity. Revised walkthrough will partially address this.
