### ISSUE TITLE
opencv ? ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#592]
trackpy 0.4.2, I must have missed the ?new? import requirement or my environment may have changed.

```
>>> import trackpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\g\test\lib\trackpy\__init__.py", line 11, in <module>
    from trackpy.api import *
  File "C:\g\test\lib\trackpy\api.py", line 26, in <module>
    from . import predict
  File "C:\g\test\lib\trackpy\predict.py", line 24, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by apiszcz** [comment]
user error, disregard
